sf2snsStart:
  handler: index.start
  timeout: 100
  memory: 256
  source: 'node_modules/@cumulus/api/dist/sfSnsBroadcast/'
  tables:
    - ExecutionsTable
  envs:
    execution_sns_topic_arn:
      function: Ref
      value: reportExecutionsSns
    granule_sns_topic_arn:
      function: Ref
      value: reportGranulesSns
    pdr_sns_topic_arn:
      function: Ref
      value: reportPdrsSns

sf2snsEnd:
  handler: index.end
  timeout: 100
  memory: 256
  source: 'node_modules/@cumulus/api/dist/sfSnsBroadcast/'
  tables:
    - ExecutionsTable
  envs:
    execution_sns_topic_arn:
      function: Ref
      value: reportExecutionsSns
    granule_sns_topic_arn:
      function: Ref
      value: reportGranulesSns
    pdr_sns_topic_arn:
      function: Ref
      value: reportPdrsSns
