default:

  # This flag specifies that this template will use the custom/overridden
  # compileCF class from the deployment package kes.js
  customCompilation: true

  # User facing options, these can be overridden in the parent template
  # configuration or the deployment app/config.yml
  lambdaProcess: true
  maxNumberOfRetainedLambdas: 1

  # This list specifies which config values will be overriden by values
  # in the parent configuration.  This allows subtemplates to have
  # user facing configuration flags
  override_with_parent:
    - maxNumberOfRetainedLambdas
    - message_adapter_version
    - useWorkflowLambdaVersions

  # This flag sets if the template will add values to the config.oldLambdaInjection
  # keys containing 'old' lambda hash/version information
  oldLambdaInjection: true

  lambdas: !!files [
  'lambdas.yml',
  'node_modules/@cumulus/api/config/lambdas.yml',
  'node_modules/@cumulus/api/config/workflowLambdas.yml'
  ]

  workflowLambdas: !!files [
  'lambdas.yml',
  'node_modules/@cumulus/api/config/workflowLambdas.yml'
  ]

  repo_owner: nasa
  message_adapter_repo: cumulus-message-adapter
  message_adapter_filename: cumulus-message-adapter.zip
